import { z } from "zod";
import type { CognitiveWorkspaceService } from "../cognitive/cognitive-workspace-service.js";
import { defineCapability } from "./schema.js";

const unit=z.number().min(0).max(1);
export function cognitiveCapabilities(service:CognitiveWorkspaceService){return[
  defineCapability({id:"cognitive.workspace.list",version:"1.0.0",description:"List durable Global Workspace cognitive objects ordered by attention priority.",risk:"pure",sideEffect:false,source:"core"},z.object({attentionState:z.enum(["queued","focused","deferred"]).optional()}),async(input,ctx)=>({objects:await service.objects(ctx.tenantId,input.attentionState)})),
  defineCapability({id:"cognitive.object.create",version:"1.0.0",description:"Create a sourced, confidence/importance-scored cognitive object without automatically executing it.",risk:"workspace_write",sideEffect:true,source:"core"},z.object({sessionId:z.string().optional(),kind:z.enum(["observation","problem","hypothesis","insight","risk","opportunity","decision"]),title:z.string().min(1).max(500),content:z.string().min(1).max(100000),sourceType:z.enum(["user","agent","event","memory","system"]),sourceId:z.string().max(500).optional(),confidence:unit,importance:unit,urgency:unit,impact:unit,userRelevance:unit,horizon:z.enum(["reactive","tactical","strategic"]),goalId:z.string().optional(),bucket:z.string().max(100).optional(),requestedTokens:z.number().int().min(100).max(10000000).optional(),requestedTimeMs:z.number().int().min(1000).optional(),tags:z.array(z.string()).max(100).optional(),relations:z.array(z.string()).max(200).optional()}),async(i,ctx)=>await service.createObject({tenantId:ctx.tenantId,kind:i.kind,title:i.title,content:i.content,sourceType:i.sourceType,confidence:i.confidence,importance:i.importance,urgency:i.urgency,impact:i.impact,userRelevance:i.userRelevance,horizon:i.horizon,...(i.sessionId?{sessionId:i.sessionId}:{}),...(i.sourceId?{sourceId:i.sourceId}:{}),...(i.goalId?{goalId:i.goalId}:{}),...(i.bucket?{bucket:i.bucket}:{}),...(i.requestedTokens!==undefined?{requestedTokens:i.requestedTokens}:{}),...(i.requestedTimeMs!==undefined?{requestedTimeMs:i.requestedTimeMs}:{}),...(i.tags?{tags:i.tags}:{}),...(i.relations?{relations:i.relations}:{})})),
  defineCapability({id:"cognitive.attention.allocate",version:"1.0.0",description:"Allocate bounded Global Workspace focus by constitutional goal class, score, token budget and focus slots.",risk:"privileged",sideEffect:true,source:"core"},z.object({}),async(_i,ctx)=>await service.allocateAttention(ctx.tenantId)),
  defineCapability({id:"cognitive.iteration.record",version:"1.0.0",description:"Record a hash-only thought iteration and block the object after repeated identical outcomes.",risk:"workspace_write",sideEffect:true,source:"core"},z.object({objectId:z.string(),result:z.string().min(1).max(100000)}),async(i,ctx)=>await service.recordIteration(ctx.tenantId,i.objectId,i.result)),
  defineCapability({id:"cognitive.intake",version:"1.0.0",description:"Automatic Global Workspace intake: deduplicated, quota-bounded observation capture from memory, world model, society, environment or initiative signals.",risk:"workspace_write",sideEffect:true,source:"core"},z.object({source:z.enum(["user","agent","event","memory","system","world-model","initiative","society","environment"]),title:z.string().min(1).max(500),content:z.string().min(1).max(100000),sourceId:z.string().max(500).optional(),kind:z.enum(["observation","problem","hypothesis","insight","risk","opportunity","decision"]).optional(),goalId:z.string().optional(),bucket:z.string().max(100).optional(),confidence:unit.optional(),importance:unit.optional(),urgency:unit.optional(),impact:unit.optional(),userRelevance:unit.optional(),horizon:z.enum(["reactive","tactical","strategic"]).optional(),tags:z.array(z.string()).max(100).optional(),dailyLimit:z.number().int().min(1).max(100000).optional()}),async(i,ctx)=>await service.intake({tenantId:ctx.tenantId,sessionId:ctx.sessionId,source:i.source,title:i.title,content:i.content,...(i.sourceId?{sourceId:i.sourceId}:{}),...(i.kind?{kind:i.kind}:{}),...(i.goalId?{goalId:i.goalId}:{}),...(i.bucket?{bucket:i.bucket}:{}),...(i.confidence!==undefined?{confidence:i.confidence}:{}),...(i.importance!==undefined?{importance:i.importance}:{}),...(i.urgency!==undefined?{urgency:i.urgency}:{}),...(i.impact!==undefined?{impact:i.impact}:{}),...(i.userRelevance!==undefined?{userRelevance:i.userRelevance}:{}),...(i.horizon?{horizon:i.horizon}:{}),...(i.tags?{tags:i.tags}:{}),...(i.dailyLimit!==undefined?{dailyLimit:i.dailyLimit}:{})})),
  defineCapability({id:"cognitive.attention.preempt",version:"1.0.0",description:"Allocate attention with preemption: a constitutionally higher-ranked object may reclaim a focused slot, releasing the preempted reservation.",risk:"privileged",sideEffect:true,source:"core"},z.object({}),async(_i,ctx)=>await service.allocateAttention(ctx.tenantId,{preempt:true})),
  defineCapability({id:"cognitive.focus.interrupt",version:"1.0.0",description:"Interrupt a focused thought and return it to the queue without losing budget accounting.",risk:"workspace_write",sideEffect:true,source:"core"},z.object({objectId:z.string(),reason:z.string().min(1).max(200)}),async(i,ctx)=>await service.interruptFocus(ctx.tenantId,i.objectId,i.reason)),
  defineCapability({id:"cognitive.reflection.schedule",version:"1.0.0",description:"Schedule a mini, deep, meta or Dream Mode reflection. Dream and meta reflection require the matching cognitive mode.",risk:"workspace_write",sideEffect:true,source:"core"},z.object({kind:z.enum(["mini","deep","meta","dream"]),focusObjectIds:z.array(z.string()).max(50).optional(),note:z.string().max(5000).optional()}),async(i,ctx)=>await service.scheduleReflection({tenantId:ctx.tenantId,kind:i.kind,...(i.focusObjectIds?{focusObjectIds:i.focusObjectIds}:{}),...(i.note?{note:i.note}:{})})),
  defineCapability({id:"cognitive.curiosity.queue",version:"1.0.0",description:"List low-confidence, high-impact hypotheses and opportunities worth investigating with spare attention.",risk:"pure",sideEffect:false,source:"core"},z.object({limit:z.number().int().min(1).max(200).optional()}),async(i,ctx)=>({queue:await service.curiosityQueue(ctx.tenantId,i.limit??20)})),
  defineCapability({id:"cognitive.health",version:"1.0.0",description:"Cognitive health and constitution check: repeated loops, focus overruns, stale strategic work, unsourced high-confidence claims and budget saturation.",risk:"pure",sideEffect:false,source:"core"},z.object({}),async(_i,ctx)=>await service.health(ctx.tenantId)),
  defineCapability({id:"cognitive.intake.log",version:"1.0.0",description:"Read the hash-only Global Workspace intake ledger.",risk:"pure",sideEffect:false,source:"core"},z.object({limit:z.number().int().min(1).max(5000).optional()}),async(i,ctx)=>({records:await service.intakeLog(ctx.tenantId,i.limit??200)})),
  defineCapability({id:"cognitive.allocation.configure",version:"1.0.0",description:"Configure the cognitive economy: named shares of the daily attention budget (for example project 0.4, research 0.25).",risk:"privileged",sideEffect:true,source:"core"},z.object({buckets:z.array(z.object({name:z.string().min(1).max(100),share:unit})).min(1).max(20)}),async(i,ctx)=>await service.configureAllocation(ctx.tenantId,i.buckets)),
  defineCapability({id:"cognitive.allocation.view",version:"1.0.0",description:"Read per-bucket attention caps, consumption and remaining budget.",risk:"pure",sideEffect:false,source:"core"},z.object({}),async(_i,ctx)=>({allocation:await service.allocationView(ctx.tenantId)})),
  defineCapability({id:"cognitive.goals.list",version:"1.0.0",description:"List constitutional P0-P4 cognitive goals.",risk:"pure",sideEffect:false,source:"core"},z.object({}),async(_i,ctx)=>({goals:await service.goals(ctx.tenantId)})),
  defineCapability({id:"cognitive.goal.create",version:"1.0.0",description:"Create a bounded constitutional cognitive goal. P0/P1 authority remains policy-gated.",risk:"privileged",sideEffect:true,source:"core"},z.object({title:z.string().min(1).max(300),objective:z.string().min(1).max(10000),class:z.enum(["P0","P1","P2","P3","P4"]),importance:unit,urgency:unit,userRelevance:unit}),async(i,ctx)=>await service.createGoal({tenantId:ctx.tenantId,...i})),
  defineCapability({id:"cognitive.goals.arbitrate",version:"1.0.0",description:"Rank active goals by constitutional class before importance, urgency and user relevance, preserving close conflicts.",risk:"workspace_write",sideEffect:true,source:"core"},z.object({}),async(_i,ctx)=>await service.arbitrateGoals(ctx.tenantId)),
  defineCapability({id:"cognitive.mode.get",version:"1.0.0",description:"Read the tenant cognitive operating mode and transition history.",risk:"pure",sideEffect:false,source:"core"},z.object({}),async(_i,ctx)=>await service.mode(ctx.tenantId)),
  defineCapability({id:"cognitive.mode.transition",version:"1.0.0",description:"Apply a constitution-checked cognitive mode transition with a durable reason.",risk:"privileged",sideEffect:true,source:"core"},z.object({mode:z.enum(["reactive","research","development","reflection","dream","emergency"]),reason:z.string().min(1).max(1000)}),async(i,ctx)=>await service.transitionMode(ctx.tenantId,i.mode,i.reason)),
];}
