import { z } from "zod";
import type { AgentSocietyService } from "../society/agent-society-service.js";
import { defineCapability } from "./schema.js";

const priority = z.enum(["critical", "high", "normal", "low"]);
export function societyCapabilities(service: AgentSocietyService) {
  return [
    defineCapability({ id: "society.roles.list", version: "1.0.0", description: "List the tenant's Aurora council, specialist and micro-agent roles with reputation and capability tags.", risk: "pure", sideEffect: false, source: "core" }, z.object({}), async (_input, context) => ({ roles: await service.roles(context.tenantId) })),
    defineCapability({ id: "society.tasks.list", version: "1.0.0", description: "List durable society marketplace tasks and bids.", risk: "pure", sideEffect: false, source: "core" }, z.object({}), async (_input, context) => ({ tasks: await service.tasks(context.tenantId) })),
    defineCapability({ id: "society.task.post", version: "1.0.0", description: "Post a bounded task to the Aurora society marketplace. This mutates durable orchestration state.", risk: "workspace_write", sideEffect: true, source: "core" }, z.object({ rootSessionId: z.string(), title: z.string().min(1).max(300), objective: z.string().min(1).max(50_000), requiredCapabilityTags: z.array(z.string()).max(100).default([]), priority: priority.default("normal"), maxTokens: z.number().int().min(100).max(10_000_000).default(100_000), deadline: z.string().datetime().optional() }), async (input, context) => await service.postTask({ tenantId: context.tenantId, rootSessionId: input.rootSessionId, title: input.title, objective: input.objective, requiredCapabilityTags: input.requiredCapabilityTags, priority: input.priority, maxTokens: input.maxTokens, ...(input.deadline ? { deadline: input.deadline } : {}) })),
    defineCapability({ id: "society.task.bid", version: "1.0.0", description: "Submit one role bid with confidence and resource estimate to an open society task.", risk: "workspace_write", sideEffect: true, source: "core" }, z.object({ taskId: z.string(), roleId: z.string(), confidence: z.number().min(0).max(1), estimatedTokens: z.number().int().positive(), estimatedDurationMs: z.number().int().positive(), rationale: z.string().min(1).max(2000) }), async (input, context) => await service.bid({ tenantId: context.tenantId, ...input })),
    defineCapability({ id: "society.task.award", version: "1.0.0", description: "Deterministically award a marketplace task under reputation, capability, cost and tenant budget rules.", risk: "workspace_write", sideEffect: true, source: "core" }, z.object({ taskId: z.string() }), async ({ taskId }, context) => await service.award(context.tenantId, taskId)),
    defineCapability({ id: "society.task.execute", version: "1.0.0", description: "Spawn the awarded profile-bound specialist as an isolated child session. Policy authority cannot exceed the parent.", risk: "privileged", sideEffect: true, source: "core" }, z.object({ taskId: z.string() }), async ({ taskId }, context) => await service.execute(context.tenantId, taskId)),
    defineCapability({ id: "society.task.pause", version: "1.0.0", description: "Pause a running society task by record: it leaves the concurrency ceiling and the stalled monitor while its token reservation is held.", risk: "workspace_write", sideEffect: true, source: "core" }, z.object({ taskId: z.string(), reason: z.string().max(2000).optional() }), async (input, context) => await service.pauseTask(context.tenantId, input.taskId, input.reason)),
    defineCapability({ id: "society.task.resume", version: "1.0.0", description: "Resume a paused society task back to running. Only paused tasks resume.", risk: "workspace_write", sideEffect: true, source: "core" }, z.object({ taskId: z.string() }), async ({ taskId }, context) => await service.resumeTask(context.tenantId, taskId)),
    defineCapability({ id: "society.task.cancel", version: "1.0.0", description: "Cancel an open, assigned, running or paused society task and release its token reservation back to the daily budget.", risk: "workspace_write", sideEffect: true, source: "core" }, z.object({ taskId: z.string(), reason: z.string().max(2000).optional() }), async (input, context) => await service.cancelTask(context.tenantId, input.taskId, input.reason)),
    defineCapability({ id: "society.deliberations.list", version: "1.0.0", description: "List multi-role deliberations, perspectives, dissent and weighted outcomes.", risk: "pure", sideEffect: false, source: "core" }, z.object({}), async (_input, context) => ({ deliberations: await service.deliberations(context.tenantId) })),
    defineCapability({ id: "society.deliberation.create", version: "1.0.0", description: "Open a bounded multi-role deliberation with an explicit quorum.", risk: "workspace_write", sideEffect: true, source: "core" }, z.object({ question: z.string().min(1).max(10_000), requiredRoleIds: z.array(z.string()).min(2).max(50), quorum: z.number().int().min(2).optional() }), async (input, context) => await service.createDeliberation({ tenantId: context.tenantId, question: input.question, requiredRoleIds: input.requiredRoleIds, ...(input.quorum !== undefined ? { quorum: input.quorum } : {}) })),
    defineCapability({ id: "society.deliberation.submit", version: "1.0.0", description: "Submit one role perspective with recommendation, confidence, rationale and evidence IDs.", risk: "workspace_write", sideEffect: true, source: "core" }, z.object({ deliberationId: z.string(), roleId: z.string(), recommendation: z.enum(["approve", "reject", "abstain"]), confidence: z.number().min(0).max(1), summary: z.string().min(1).max(10_000), evidenceEventIds: z.array(z.string()).max(200).default([]) }), async (input, context) => await service.submitPerspective({ tenantId: context.tenantId, ...input })),
    defineCapability({ id: "society.bus.publish", version: "1.0.0", description: "Publish a bounded message on the Agent Communication Bus to named roles or the whole society.", risk: "workspace_write", sideEffect: true, source: "core" }, z.object({ fromRoleId: z.string(), topic: z.string().min(1).max(200), body: z.string().min(1).max(20_000), audienceRoleIds: z.array(z.string()).max(50).optional(), taskId: z.string().optional(), deliberationId: z.string().optional(), importance: z.number().min(0).max(1).optional() }), async (input, context) => await service.broadcast({ tenantId: context.tenantId, fromRoleId: input.fromRoleId, topic: input.topic, body: input.body, ...(input.audienceRoleIds ? { audienceRoleIds: input.audienceRoleIds } : {}), ...(input.taskId ? { taskId: input.taskId } : {}), ...(input.deliberationId ? { deliberationId: input.deliberationId } : {}), ...(input.importance !== undefined ? { importance: input.importance } : {}) })),
    defineCapability({ id: "society.bus.inbox", version: "1.0.0", description: "Read the communication-bus messages addressed to one role.", risk: "pure", sideEffect: false, source: "core" }, z.object({ roleId: z.string(), unacknowledgedOnly: z.boolean().optional(), limit: z.number().int().min(1).max(1000).optional() }), async (input, context) => ({ messages: await service.inbox(context.tenantId, input.roleId, { ...(input.unacknowledgedOnly !== undefined ? { unacknowledgedOnly: input.unacknowledgedOnly } : {}), ...(input.limit ? { limit: input.limit } : {}) }) })),
    defineCapability({ id: "society.bus.acknowledge", version: "1.0.0", description: "Acknowledge a communication-bus message as a role.", risk: "workspace_write", sideEffect: true, source: "core" }, z.object({ messageId: z.string(), roleId: z.string() }), async (input, context) => await service.acknowledgeMessage(context.tenantId, input.messageId, input.roleId)),
    defineCapability({ id: "society.meta.monitor", version: "1.0.0", description: "Meta-agent monitoring: stalled or duplicated tasks, unbid work, failing or idle roles, budget saturation and concurrency starvation.", risk: "pure", sideEffect: false, source: "core" }, z.object({ stalledAfterMs: z.number().int().min(60_000).optional(), idleAfterMs: z.number().int().min(60_000).optional() }), async (input, context) => await service.metaMonitor(context.tenantId, { ...(input.stalledAfterMs !== undefined ? { stalledAfterMs: input.stalledAfterMs } : {}), ...(input.idleAfterMs !== undefined ? { idleAfterMs: input.idleAfterMs } : {}) })),
    defineCapability({ id: "society.roles.retire-underperformers", version: "1.0.0", description: "Retire non-builtin roles whose evidence-bound failure rate exceeds the policy threshold.", risk: "privileged", sideEffect: true, source: "core" }, z.object({ minAttempts: z.number().int().min(1).max(1000).optional(), maxFailureRate: z.number().min(0).max(1).optional() }), async (input, context) => ({ retired: await service.retireUnderperformers(context.tenantId, { ...(input.minAttempts !== undefined ? { minAttempts: input.minAttempts } : {}), ...(input.maxFailureRate !== undefined ? { maxFailureRate: input.maxFailureRate } : {}) }) })),
    defineCapability({ id: "society.deliberation.resolve", version: "1.0.0", description: "Resolve a quorum deliberation by reputation/confidence weight while preserving dissent and missing perspectives.", risk: "workspace_write", sideEffect: true, source: "core" }, z.object({ deliberationId: z.string() }), async ({ deliberationId }, context) => await service.resolveDeliberation(context.tenantId, deliberationId)),
  ];
}
