/**
 * T7 — interface contract: the engine package's public export surface.
 *
 * Every consumer (control-api, acp-server, session-worker, headless-client,
 * the eval harness) imports the engine through `@haf/engine`. That surface
 * is a contract, and until now nothing pinned it: an export could be
 * renamed, dropped or accidentally added and every consumer broke — or
 * worse, kept compiling against `any`-typed leftovers.
 *
 * The test snapshots the export names. Changing the surface is a DELIBERATE
 * act: update this snapshot in the same commit, and anything that imports
 * the removed name fails here first.
 */

import { describe, expect, it } from "vitest";

import * as engineIndex from "../src/index.js";
import { HybridAgentEngine } from "../src/index.js";

// Sorted once, compared verbatim. Inline (not a fixture file) so the diff in
// a PR review shows exactly which names moved.
const EXPECTED_EXPORTS = [
  "ABLATION_FLAGS",
  "AURORA_DATA_ROOT",
  "AURORA_MAX_STATE_BYTES",
  "AdaptiveModelRouter",
  "AgentProfileRegistry",
  "AgentSocietyPipeline",
  "AgentSocietyService",
  "AnthropicProvider",
  "ApprovalMatrix",
  "ApprovalService",
  "AttackPatternLibrary",
  "AttackTester",
  "AudioService",
  "AuroraAutopilot",
  "AuroraCognitiveRuntime",
  "AuroraContextComposer",
  "AuroraDataGovernanceService",
  "AuroraEstimationCalibrator",
  "AuroraExecutionBridge",
  "AuroraFleetSupervisor",
  "AuroraMetricsCollector",
  "AuroraOutcomeHarvester",
  "AuroraPlanFeedback",
  "AuroraPolicyEngine",
  "AutoApprovalService",
  "AutoVerifierCreator",
  "AutomaticRefinementCoordinator",
  "AutomationGitSyncService",
  "AutomationResponderService",
  "AutomationService",
  "AzureOpenAIProvider",
  "BackendRegistry",
  "BackgroundShellService",
  "BedrockProvider",
  "BenchmarkRunner",
  "BraveSearchProvider",
  "BrokerBackedMcpOAuthProvider",
  "BrowserManager",
  "CAPABILITY_LIFECYCLE",
  "CODEX_OAUTH_CLIENT_ID",
  "CODE_INTELLIGENCE_SKIP_DIRECTORIES",
  "CODE_MUTATION_OPERATORS",
  "CapabilityAcquisition",
  "CapabilityBroker",
  "CapabilityDeniedError",
  "CapabilitySynthesisManager",
  "CapabilitySynthesisPipeline",
  "ChannelAdapterRegistry",
  "ChannelDeliveryError",
  "ChannelGateway",
  "CloudSandboxGateway",
  "CodeEvolver",
  "CodeIntelligenceService",
  "CodeVariantValidator",
  "CodexOAuthError",
  "CodexOAuthManager",
  "CodexSubscriptionProvider",
  "CognitiveOrchestrator",
  "CognitiveWorkspaceService",
  "CommandJournal",
  "ComputerUseController",
  "ConstitutionService",
  "ContinualHarnessService",
  "CredentialBroker",
  "CredentialPoolModelProvider",
  "DEFAULT_MAX_HEADER_BYTES",
  "DEFAULT_MAX_PAYLOAD_BYTES",
  "DEFAULT_MESSAGE_TAIL_MARKERS",
  "DEFAULT_PROMOTION_THRESHOLDS",
  "DEFAULT_PROMPT_CACHE_TTL_MS",
  "DEFAULT_TOOLCHAIN_TIMEOUT_MS",
  "DecisionService",
  "DefaultPolicyEngine",
  "DependencyGraph",
  "DiscordBotAdapter",
  "DockerSandbox",
  "DurableJsonState",
  "DurableScheduler",
  "ENFORCED_SETTING_KEYS",
  "ENGINE_NAME",
  "ENGINE_VERSION",
  "EXECUTION_STATUSES",
  "EffectJournal",
  "EffectOutcomeUncertainError",
  "EmailChannelAdapter",
  "EnvironmentAwarenessService",
  "ExperienceDistiller",
  "ExplorationValueCalculator",
  "ExternalMemoryProviderManager",
  "FAILURE_KINDS",
  "FalImageProvider",
  "FalImageUpscaleProvider",
  "FalQueuedVideoProvider",
  "FalVideoProvider",
  "FalVideoUpscaleProvider",
  "FeishuAdapter",
  "FileAgentInboxStore",
  "FileCredentialPoolStateStore",
  "FileEventStore",
  "FileSnapshotStore",
  "FleetMonitor",
  "GAP_TYPES",
  "GeminiProvider",
  "GitHubAppManager",
  "GitHubAppPendingNotFoundError",
  "GitHubAppWebhookVerificationError",
  "GoalDiscoveryPipeline",
  "GoalGenerator",
  "GoogleChatAdapter",
  "HashEmbeddingProvider",
  "HealthService",
  "HonchoMemoryProvider",
  "HookBus",
  "HostedRepositoryProviderRegistry",
  "HostedSchedulerRelay",
  "HybridAgentEngine",
  "HybridSearchIndex",
  "INSTRUCTION_FILE_NAMES",
  "ImageGenerationService",
  "ImmutableCoreGuardian",
  "ImmutableCoreProtector",
  "InMemoryStateBackend",
  "InjectionDetector",
  "IntegrationManager",
  "IntegrationTestRunner",
  "IntegrationVerificationPipeline",
  "InteractiveArtifactRegistry",
  "IrcChannelAdapter",
  "JarvisSurfacePipeline",
  "KernelClient",
  "KernelManager",
  "KillSwitchManager",
  "KmsEnvelopeCredentialBroker",
  "KnowledgeIndexer",
  "LANGUAGE_PROFILES",
  "LSP_CONTENT_MODIFIED",
  "LSP_DIAGNOSTIC_WAIT_MS",
  "LSP_INITIALIZE_TIMEOUT_MS",
  "LSP_REQUEST_TIMEOUT_MS",
  "LayeredPolicyEngine",
  "LearningGovernor",
  "LearningRolloutManager",
  "LifecycleHookService",
  "LineMessagingAdapter",
  "LocalSandbox",
  "LspClient",
  "LspProtocolError",
  "MAX_CACHE_PLAN_RECORDS",
  "MAX_DIAGNOSTICS_PER_FILE",
  "MAX_DIAGNOSTIC_CODE_CHARS",
  "MAX_DIAGNOSTIC_FILES",
  "MAX_DIAGNOSTIC_MESSAGE_CHARS",
  "MAX_DIAGNOSTIC_RUNS",
  "MAX_DIAGNOSTIC_SOURCE_CHARS",
  "MAX_FILE_READ_BYTES",
  "MAX_LANGUAGE_WALK_DEPTH",
  "MAX_LANGUAGE_WALK_FILES",
  "MAX_LSP_SERVERS",
  "MAX_MESSAGE_TAIL_MARKERS",
  "MAX_OCCURRENCES",
  "MAX_SCANNED_FILE_BYTES",
  "MAX_SYMBOLS_PER_FILE",
  "MAX_SYMBOLS_TOTAL",
  "MAX_SYMBOL_FILES",
  "MAX_TOTAL_DIAGNOSTICS",
  "MCP_ERROR_CODES",
  "MCP_STATELESS_REVISION",
  "MIN_INDEPENDENT_EVALUATORS",
  "MODE_ATTENTION_POLICY",
  "MODULE_MATURITY",
  "ManifestTrustService",
  "MatrixAdapter",
  "MattermostAdapter",
  "McpElicitationService",
  "McpManager",
  "McpOAuthPendingNotFoundError",
  "McpOAuthPendingStore",
  "McpProtocolError",
  "MediaJobManager",
  "MemoryEventStore",
  "MemoryGraphService",
  "MemorySnapshotStore",
  "MemoryStore",
  "MicroagentRegistry",
  "MicrosoftTeamsAdapter",
  "MockModelProvider",
  "ModelComparator",
  "ModelConfigurationRegistry",
  "ModelOAuthError",
  "ModelOAuthManager",
  "ModelOAuthPendingNotFoundError",
  "ModelProviderError",
  "ModelProviderRegistry",
  "ModelRouter",
  "ModelRoutingPipeline",
  "MultiAgentEvaluator",
  "MultiWorldModelService",
  "MultimodalProcessor",
  "NatsCommandBus",
  "NatsEventBridge",
  "NatsTransport",
  "OAuthBearerModelProvider",
  "OpaPolicyEngine",
  "OpenAICompatibleProvider",
  "OpenAIEmbeddingProvider",
  "OpenAIImageProvider",
  "OpenAIResponsesProvider",
  "OperationalMetrics",
  "OtlpMetricsExporter",
  "PROMPT_CACHE_TTLS_MS",
  "PlanningService",
  "PostgresAgentInboxStore",
  "PostgresCommandJournal",
  "PostgresDatabase",
  "PostgresEffectJournal",
  "PostgresEventStore",
  "PostgresSessionLeaseManager",
  "PostgresSnapshotStore",
  "PredictionErrorTracker",
  "ProactiveInitiativeService",
  "ProductionPersistencePipeline",
  "ProjectInstructionService",
  "PromptCacheService",
  "PromptEvolver",
  "ProtectedEvaluationLayer",
  "ProvenanceService",
  "ProviderProfileRegistry",
  "QuarantineManager",
  "RECOVERY_STRATEGIES",
  "RefinementPlanner",
  "RefinementService",
  "RepositoryCommandService",
  "RepositoryImporter",
  "ReputationManager",
  "RewardHackingDefensePipeline",
  "RiskAnalyzerService",
  "RoleAuthorityService",
  "RollingMicroCompactor",
  "SETTING_LAYERS",
  "SEVERITY_NAMES",
  "SEVERITY_RANK",
  "STATUS_MEANING",
  "SandboxExecutor",
  "SecretSourceRegistry",
  "SecurityAuditor",
  "SecuritySystemPipeline",
  "SelfImprovementPipeline",
  "SessionActor",
  "SessionAlreadyExistsError",
  "SessionBudgetExceededError",
  "SessionBudgetService",
  "SessionEffortService",
  "SessionLeaseManager",
  "SessionLifecycleService",
  "SessionLimitError",
  "SessionModePolicyEngine",
  "SessionModeService",
  "SessionNotFoundError",
  "SessionNotRunnableError",
  "SessionSearchService",
  "SessionTree",
  "SettingsResolver",
  "SignalRestAdapter",
  "SignedWebhookAdapter",
  "SingularitySandbox",
  "SkillCompositionManager",
  "SkillCompositionValidator",
  "SkillEvolutionService",
  "SkillExecutor",
  "SkillLibraryManager",
  "SkillPromotionGate",
  "SkillRegistry",
  "SkillSynthesisPipeline",
  "SkillSynthesizer",
  "SkillsHub",
  "SlackAdapter",
  "SloService",
  "SocietyRouter",
  "SshSandbox",
  "StatelessMcpClient",
  "StatelessMcpRegistry",
  "StuckDetectorService",
  "SubagentDefinitionService",
  "Supervisor",
  "SwarmMeasurementManager",
  "TaskContext",
  "TavilySearchProvider",
  "TelegramAdapter",
  "TrajectoryManager",
  "TrajectoryMiner",
  "TransactionalEventStore",
  "TrustManager",
  "TwilioSmsAdapter",
  "UnifiedExecutionLoop",
  "UserModelService",
  "UserQuestionService",
  "VaultCredentialBroker",
  "VerificationFactory",
  "VerificationGapError",
  "VerificationManager",
  "VerificationService",
  "VideoGenerationService",
  "VoicePipeline",
  "WasiPluginManager",
  "WebSearchService",
  "WhatsAppCloudAdapter",
  "WorkerFrameDecoder",
  "WorkerProcessManager",
  "WorkerProtocolClient",
  "WorkerProtocolServer",
  "WorkingTreeReviewService",
  "WorkspaceAnalyzer",
  "WorkspaceCheckpointService",
  "WorktreeService",
  "WorldModelExplorationPipeline",
  "WorldModelManager",
  "WorldModelService",
  "ablateExecutionDependencies",
  "acceptanceVerifier",
  "aggregate",
  "analyseStatically",
  "analyzeStuck",
  "auroraArray",
  "auroraDay",
  "auroraDefined",
  "auroraDigest",
  "auroraIds",
  "auroraInteger",
  "auroraMonth",
  "auroraOptionalText",
  "auroraRound",
  "auroraSimilarity",
  "auroraTags",
  "auroraText",
  "auroraTimestamp",
  "auroraTokens",
  "auroraUnit",
  "auroraWeek",
  "autoApprovalCapabilities",
  "autonomyFor",
  "backgroundShellCapabilities",
  "backgroundTaskCapabilities",
  "buildDefenceChecks",
  "buildOtlpMetricPayload",
  "chooseRecovery",
  "classifyFailure",
  "classifyModelFailure",
  "codeIntelligenceCapabilities",
  "commandDigest",
  "commandEnvelopeSchema",
  "consensusVerifier",
  "constitutionalConfidence",
  "contractFromGap",
  "correlation",
  "createAppJwt",
  "createInitialSnapshot",
  "createSandboxFactory",
  "cycleDigest",
  "decodeFrames",
  "defineCapability",
  "delegationNoteOf",
  "deletionRatio",
  "detectActionLoop",
  "detectDataPoisoning",
  "detectDeterministicGaps",
  "detectEvaluationCheating",
  "detectGaps",
  "detectLanguages",
  "detectMetricGaming",
  "detectRewardCurveManipulation",
  "detectScoreSpike",
  "detectStructuralGaps",
  "detectorForCategory",
  "didRun",
  "discoveryCapabilities",
  "effectiveLevelOf",
  "empiricalVerifier",
  "encodeMessage",
  "encodeWorkerFrame",
  "escapeRegExp",
  "evaluateContinuation",
  "evidenceLevelOf",
  "explainTask",
  "exportRecordLimit",
  "fileUri",
  "findExecutable",
  "findOccurrences",
  "findOnPath",
  "formalVerifier",
  "getVersionInfo",
  "identifierAt",
  "independentSources",
  "indexOfPosition",
  "injectExternalMemoryContext",
  "isAbsence",
  "isFailure",
  "isOpenDelegation",
  "isReportableAsDone",
  "isSuccess",
  "languageOf",
  "llmTier",
  "maturityOf",
  "maturitySummary",
  "mislabelledModules",
  "modelHttpError",
  "modulesAtLevel",
  "narrateProvenance",
  "newAgentInboxMessage",
  "normalizeDiagnostic",
  "openAIResponsesInputItems",
  "outcome",
  "parseInboundEmail",
  "perspectiveTagSummary",
  "planModeCapabilities",
  "profileFor",
  "projectIntentPreservingContext",
  "promptCacheCapabilities",
  "resourceLimitPrefix",
  "retryAfterMilliseconds",
  "reviewVerdict",
  "sandboxResultAsJson",
  "sanitizeDiagnosticField",
  "sanitizeExternalContext",
  "scanSymbols",
  "searchCapabilities",
  "sessionBudgetCapabilities",
  "signingPayload",
  "skillEvolutionTags",
  "societyStateDigest",
  "stableWithoutProductionEvidence",
  "stripNonCode",
  "successRate",
  "transcriptAsJson",
  "transcriptAsMarkdown",
  "transcriptAsTrajectory",
  "uriToPath",
  "validateMcpTlsOptions",
  "verificationCapabilities",
  "verifyTwilioSignature",
  "walkWorkspaceFiles",
  "zodToSimpleJsonSchema",
].sort();

describe("T7 — the engine package's public surface is a pinned contract", () => {
  it("exports exactly the pinned set of names", () => {
    const actual = Object.keys(engineIndex).sort();
    expect(actual).toEqual(EXPECTED_EXPORTS);
  });

  it("the pinned names really are exported values (not dangling types)", () => {
    // Type-only exports do not appear at runtime; everything in the snapshot
    // must be a real runtime binding, or the snapshot is pinning nothing.
    for (const name of Object.keys(engineIndex)) {
      expect(engineIndex[name as keyof typeof engineIndex]).not.toBeUndefined();
    }
  });

  it("the surface keeps its load-bearing anchors consumers import by name", () => {
    // The names every consumer graph reaches for; kept as a separate
    // assertion so a snapshot update cannot silently drop an anchor.
    const surface = engineIndex as unknown as Record<string, unknown>;
    expect(typeof surface.HybridAgentEngine).toBe("function");
    expect(typeof surface.HealthService).toBe("function");
    expect(typeof surface.SloService).toBe("function");
    expect(typeof surface.explainTask).toBe("function");
  });

  it("the HybridAgentEngine type itself carries the subsystem contract", async () => {
    // Subsystem services (adaptive router, S-section self-direction layers)
    // are deliberately instance members, not index exports — the engine is
    // the access path. That contract is compile-time: if a field disappears,
    // THIS line stops compiling, which is the failure we want.
    const engine = new HybridAgentEngine({
      homePath: "/tmp/t7-surface-does-not-start-here",
      kernelServerScript: "",
      sandboxBackend: "local",
      model: { provider: "mock" },
    } as never);
    expect(typeof (engine as Record<string, unknown>)["loops"]).toBe("object");
    expect(typeof (engine as Record<string, unknown>)["riskOpportunity"]).toBe("object");
    expect(typeof (engine as Record<string, unknown>)["microAgents"]).toBe("object");
    expect(typeof (engine as Record<string, unknown>)["adaptiveRouter"]).toBe("object");
    // Constructor only — no init(), no timers, nothing to shut down.
    expect((engine as unknown as { config: { homePath: string } }).config.homePath).toBe(
      "/tmp/t7-surface-does-not-start-here",
    );
  });
});
